### PR TITLE
Animate GUI

### LINKED ISSUE #47: Integrate TMX Parsing with GameMap
Take the TMX parsed map from #46 and integrate it with the GameMap class, refactored from #42 .

### LINKED ISSUE #54: Draw sample animation for game

### LINKED ISSUE #55: Closing the game should stop the engine.
Currently, the engine continues to tick after closing the game.  This should not happen.

### PR DESCRIPTION
**Pull request by seanbrais**
Closes #55.  Closes #54 .  Closes #47. Creates an animated sample game when user clicks on screen.

### CODE REVIEW

**Comment by islanddove** [comment]
@seanbrais does this run locally on your system?

**Comment by seanbrais** [comment]
It does.  Are you having issues running it?

**Comment by islanddove** [comment]
Verifying on my machine now.

**Review by j3kstrum — CHANGES_REQUESTED** [review]
- Please comment getPlayerTiles
- Please comment (explain) startUIUpdateThread's internals. It's not tough to understand but a comment might save us in a few weeks if we forget what it does.

Other methods are fine since they are either documented or do not use external libraries (external libraries should probably have better documentation surrounding their usage).

**Review by j3kstrum — APPROVED** [review]
Thank you

**Comment by islanddove** [comment]
Looks good!

**Pull request merged**
