### PR TITLE
Add VASTLY superior ticking functionality.

### LINKED ISSUE #28: Improve Ticking
Add more functionality to ticking. In particular, begin stubbing out what should be done at each tick.

### PR DESCRIPTION
**Pull request by j3kstrum**
Also fill out some nested file structures and added some stubs for other sections of the code.
Closes #28 .

### CODE REVIEW

**Review by nmartin5 — CHANGES_REQUESTED** [review]
Method names should be verbs/verb phrases simply to improve readability.  One example exists in engine/access/extern/EngineToScripting.java where method 'nextTurn' is requesting information.  For this reason, the method should be named 'getNextTurn' as the next turn is being retrieved from another source.  Same change should occur in scripting/access/ScriptingAccess.java.  The overall code looks good and is well documented.

**Comment by nmartin5** [comment]
_Just being a pain_

**Comment by j3kstrum** [comment]
Do I actually have to change this

**Comment by j3kstrum** [comment]
Leaving this open for nitpicking reasons is going to adversely affect development in the other sections of the code. I advise against this going forward, but will make these changes.

**Review by nmartin5 — APPROVED** [review]

**Comment by nmartin5** [comment]
merged. point made.

**Pull request merged**
